DROP TABLE IF EXISTS users;

CREATE TABLE users(
    uid SERIAL PRIMARY KEY,
    email VARCHAR(300) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    "firstName" VARCHAR(200) NOT NULL,
    "lastName" VARCHAR (200) NOT NULL,
    "profilePic" VARCHAR(300),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
